"""empty message

Revision ID: 1bd8afe10204
Revises: 10d978d3a8e
Create Date: 2013-09-26 21:32:34.543861

"""

# revision identifiers, used by Alembic.
revision = '1bd8afe10204'
down_revision = '10d978d3a8e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'roles_users')
    op.drop_table(u'roles')
    op.drop_column('users', u'last_login_at')
    op.drop_column('users', u'login_count')
    op.drop_column('users', u'current_login_at')
    op.drop_column('users', u'current_login_ip')
    op.drop_column('users', u'last_login_ip')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'last_login_ip', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column(u'current_login_ip', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column(u'current_login_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column(u'login_count', mysql.INTEGER(display_width=11), nullable=True))
    op.add_column('users', sa.Column(u'last_login_at', sa.DATETIME(), nullable=True))
    op.create_table(u'roles',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column(u'description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'roles_users',
    sa.Column(u'user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], name=u'roles_users_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'roles_users_ibfk_2'),
    sa.PrimaryKeyConstraint(),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
