"""Initial setup

Revision ID: 4d9d4473f57f
Revises: None
Create Date: 2013-07-26 16:08:36.493692

"""

# revision identifiers, used by Alembic.
revision = '4d9d4473f57f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('short_title', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('update_frequency', sa.Integer(), nullable=True),
    sa.Column('metadata_update', sa.DateTime(), nullable=True),
    sa.Column('parser_function', sa.String(length=50), nullable=True),
    sa.Column('favicon', sa.String(length=1024), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journals_categories',
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.String(length=1024), nullable=True),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('papers')
    op.drop_table('journals_categories')
    op.drop_table('journals')
    op.drop_table('categories')
    ### end Alembic commands ###
