"""removed id column from userpapers table

Revision ID: 563774a326d5
Revises: 4e860e37bb37
Create Date: 2013-10-05 11:28:25.770211

"""

# revision identifiers, used by Alembic.
revision = '563774a326d5'
down_revision = '4e860e37bb37'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userpapers', u'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpapers', sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
