"""Added created column to userpapers

Revision ID: 56f2aeb28bd4
Revises: 563774a326d5
Create Date: 2013-10-05 14:23:25.085533

"""

# revision identifiers, used by Alembic.
revision = '56f2aeb28bd4'
down_revision = '563774a326d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpapers', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userpapers', 'created')
    ### end Alembic commands ###
