"""empty message

Revision ID: 10d978d3a8e
Revises: 28da60aaf274
Create Date: 2013-09-22 17:34:17.704238

"""

# revision identifiers, used by Alembic.
revision = '10d978d3a8e'
down_revision = '28da60aaf274'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions_users')
    ### end Alembic commands ###
