"""Added support for subcategories in the categories table

Revision ID: 28da60aaf274
Revises: 4f3d22afbf74
Create Date: 2013-08-14 19:09:58.994193

"""

# revision identifiers, used by Alembic.
revision = '28da60aaf274'
down_revision = '4f3d22afbf74'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_column('categories', u'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column(u'description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('categories', 'parent_id')
    ### end Alembic commands ###
