"""Changed paper attributes

Revision ID: 4f3d22afbf74
Revises: 56e4c186b96d
Create Date: 2013-08-12 21:18:41.248281

"""

# revision identifiers, used by Alembic.
revision = '4f3d22afbf74'
down_revision = '56e4c186b96d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('ref', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'ref')
    ### end Alembic commands ###
